### ISSUE TITLE
Improve Device Monitor UI

### ISSUE THREAD

**Issue by nuntipat** [InGarage/MakerPlayGround#3]
### Description
This issue will move the "Device Monitor" dialog into its own tab called the "Monitor" tab. 

### Task
- [x] Create the "Monitor" tab and move UI from the dialog into the tab
- [x] Add chart UI to plot value from the device
- [x] Update style of the UI
- [x] Add VALUE as the new log level to filter only value that can be plotted in the device monitor

**Comment by nuntipat** [comment]
Done and merged in f4d5f23507d71e235004a4beefd728e042fe52c5
