### ISSUE TITLE
Implement Interactive Device Exploration Mode

### ISSUE THREAD

**Issue by nuntipat** [InGarage/MakerPlayGround#4]
### Description
This issue adds the new interactive device exploration mode to allow realtime control of the actual hardware directly from the circuit diagram and the Maker Playground's diagram.

### Task
- [x] Implement interactive code generator for the Arduino platform
- [x] Add interactive control (port selection, start/stop button) to the toolbar
- [x] Add interactive control to the diagram to allow realtime control from the diagram
- [x] Add interactive control to the circuit diagram to allow realtime control without creating the diagram
- [x] Add support for virtual and cloud device
- [x] Draw interactive control based on actual device's compatibility instead of the generic device

**Comment by jetstreamc** [comment]
Currently, the unused devices support the interactive mode. You can now draw control of all kinds of devices.

**Comment by nuntipat** [comment]
Done and merged in f4d5f23507d71e235004a4beefd728e042fe52c5
