### ISSUE TITLE
Add support for Python and SBC e.g. Raspberry Pi

### ISSUE THREAD

**Issue by nuntipat** [InGarage/MakerPlayGround#5]
### Description
This issue adds support for the Python programming language and Linux Single Board Computer such as the Raspberry Pi. Note that some of these functionalities have been added in the previous version of Maker Playground but they have been removed as they are not compatible with and other systems such as the device monitor, interactive mode and project exporter.

### Task
- [x] Add Python code generator
- [ ] Add interactive code generator for the Python platform
- [ ] Allow export python code
- [ ] Update style of the upload UI
